<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\User;
use Hash;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $employees = [
            // [
            //     'person_id' => 15848,
            //     'nik' => '71025',
            //     'name' => 'Fithri Novida',
            //     'title' =>'Principal Talent and Learning',
            //     'organization' => 'Talent and Learning Expert Team',
            //     'band' => 4,
            //     'nik_atasan' => '320005',
            //     'nama_atasan' => 'Mukhammad Atiqurrakhman',
            //     'email' => 'Fithri_Novida@telkomsel.co.id'  ,
            //     'section' => null,
            //     'department' => null,
            //     'division' => 'Talent and Learning Expert Team',
            //     'bgroup' => 'People Strategic Management Group',
            //     'egroup' => null,
            //     'directorate' => 'Human Capital Management Directorate',
            //     'admins' => 'HEAD OFFICE',
            //     'area_group' => 'HEAD OFFICE',
            // ],
            // [
            //     'person_id' => 18483,
            //     'nik' => '81029',
            //     'name' => 'Nahdatul Choir',
            //     'title' =>'Senior Learning Architect',
            //     'organization' => 'Talent and Learning Expert Team',
            //     'band' => 3,
            //     'nik_atasan' => '71025',
            //     'nama_atasan' => 'Fithri Novida',
            //     'email' => 'Nahdatul_Choi@telkomsel.co.id',
            //     'section' => null,
            //     'department' => null,
            //     'division' => 'Talent and Learning Expert Team',
            //     'bgroup' => 'People Strategic Management Group',
            //     'egroup' => null,
            //     'directorate' => 'Human Capital Management Directorate',
            //     'admins' => 'HEAD OFFICE',
            //     'area_group' => 'HEAD OFFICE',
            // ],
            // [
            //     'person_id' => 267445,
            //     'nik' => '87113',
            //     'name' => 'Eka Mariska Annisyah',
            //     'title' =>'Talent and Learning Architect',
            //     'organization' => 'Talent and Learning Expert Team',
            //     'band' => 2,
            //     'nik_atasan' => '71025',
            //     'nama_atasan' => 'Fithri Novida',
            //     'email' => 'eka_m_annisyah@telkomsel.co.id',
            //     'section' => null,
            //     'department' => null,
            //     'division' => 'Talent and Learning Expert Team',
            //     'bgroup' => 'People Strategic Management Group',
            //     'egroup' => null,
            //     'directorate' => 'Human Capital Management Directorate',
            //     'admins' => 'HEAD OFFICE',
            //     'area_group' => 'HEAD OFFICE',
            // ],
            // [
            //     'person_id' => 390637,
            //     'nik' => '92038',
            //     'name' => 'Tara Aisya Ramadhian',
            //     'title' =>'Talent and Learning Architect',
            //     'organization' => 'Talent and Learning Expert Team',
            //     'band' => 2,
            //     'nik_atasan' => '71025',
            //     'nama_atasan' => 'Fithri Novida',
            //     'email' => 'tara_a_ramadhiani@telkomsel.co.id',
            //     'section' => null,
            //     'department' => null,
            //     'division' => 'Talent and Learning Expert Team',
            //     'bgroup' => 'People Strategic Management Group',
            //     'egroup' => null,
            //     'directorate' => 'Human Capital Management Directorate',
            //     'admins' => 'HEAD OFFICE',
            //     'area_group' => 'HEAD OFFICE',
            // ],
            // [
            //     'person_id' => 396032,
            //     'nik' => '92101',
            //     'name' => 'Satya Wicaksana Mukhlisin',
            //     'title' =>'Training and Knowledge System Operations Officer',
            //     'organization' => 'Training and Knowledge System Operations Department',
            //     'band' => 2,
            //     'nik_atasan' => '83391',
            //     'nama_atasan' => 'Ivan Yuditia',
            //     'email' => 'satya_w_mukhlisin@telkomsel.co.id',
            //     'section' => null,
            //     'department' => 'Training and Knowledge System Operations Department',
            //     'division' => 'HC BP Delivery and Support Division',
            //     'bgroup' => 'HC Business Partner Group',
            //     'egroup' => null,
            //     'directorate' => 'Human Capital Management Directorate',
            //     'admins' => 'HEAD OFFICE',
            //     'area_group' => 'HEAD OFFICE',
            // ],
            // [
            //     'person_id' => 397121,
            //     'nik' => '93075',
            //     'name' => 'Annisa Noor Rahmatika',
            //     'title' =>'Staff Training and Knowledge System Operations',
            //     'organization' => 'Training and Knowledge System Operations Department',
            //     'band' => 1,
            //     'nik_atasan' => '83391',
            //     'nama_atasan' => 'Ivan Yuditia',
            //     'email' => 'Annisa_N_Rahmatika@telkomsel.co.id',
            //     'section' => null,
            //     'department' => 'Training and Knowledge System Operations Department',
            //     'division' => 'HC BP Delivery and Support Division',
            //     'bgroup' => 'HC Business Partner Group',
            //     'egroup' => null,
            //     'directorate' => 'Human Capital Management Directorate',
            //     'admins' => 'HEAD OFFICE',
            //     'area_group' => 'HEAD OFFICE',
            // ],
            // [
            //     'person_id' => 398708,
            //     'nik' => '93123',
            //     'name' => 'Joshua Rydley',
            //     'title' =>'Staff Training and Knowledge System Operations',
            //     'organization' => 'Training and Knowledge System Operations Department',
            //     'band' => 2,
            //     'nik_atasan' => '83391',
            //     'nama_atasan' => 'Ivan Yuditia',
            //     'email' => 'joshua_rydley@telkomsel.co.id',
            //     'section' => null,
            //     'department' => 'Training and Knowledge System Operations Department',
            //     'division' => 'HC BP Delivery and Support Division',
            //     'bgroup' => 'HC Business Partner Group',
            //     'egroup' => null,
            //     'directorate' => 'Human Capital Management Directorate',
            //     'admins' => 'HEAD OFFICE',
            //     'area_group' => 'HEAD OFFICE',
            // ],
            // [
            //     'person_id' => 68236,
            //     'nik' => '82358',
            //     'name' => 'Ivren Miraharza Harahap',
            //     'title' =>'Training and Knowledge System Operations Officer',
            //     'organization' => 'Training and Knowledge System Operations Department',
            //     'band' => 2,
            //     'nik_atasan' => '83391',
            //     'nama_atasan' => 'Ivan Yuditia',
            //     'email' => 'ivren_m_harahap@telkomsel.co.id',
            //     'section' => null,
            //     'department' => 'Training and Knowledge System Operations Department',
            //     'division' => 'HC BP Delivery and Support Division',
            //     'bgroup' => 'HC Business Partner Group',
            //     'egroup' => null,
            //     'directorate' => 'Human Capital Management Directorate',
            //     'admins' => 'HEAD OFFICE',
            //     'area_group' => 'HEAD OFFICE',
            // ],
            // [
            //     'person_id' => 70475,
            //     'nik' => '85028',
            //     'name' => 'Fuad Rahadi',
            //     'title' =>'Senior Talent and Career Architect',
            //     'organization' => 'Talent and Learning Expert Team',
            //     'band' => 3,
            //     'nik_atasan' => '71025',
            //     'nama_atasan' => 'Fithri Novida',
            //     'email' => 'Fuad_Rahadi@telkomsel.co.id',
            //     'section' => null,
            //     'department' => null,
            //     'division' => 'Talent and Learning Expert Team',
            //     'bgroup' => 'People Strategic Management Group',
            //     'egroup' => null,
            //     'directorate' => 'Human Capital Management Directorate',
            //     'admins' => 'HEAD OFFICE',
            //     'area_group' => 'HEAD OFFICE',
            // ],
            // [
            //     'person_id' => 73874,
            //     'nik' => '85065',
            //     'name' => 'Vestiyana Rimayumanti',
            //     'title' =>'Training and Knowledge System Operations Officer',
            //     'organization' => 'Training and Knowledge System Operations Department',
            //     'band' => 2,
            //     'nik_atasan' => '83391',
            //     'nama_atasan' => 'Ivan Yuditia',
            //     'email' => 'Vestiyana_Rimayumanti@telkomsel.co.id',
            //     'section' => null,
            //     'department' => 'Training and Knowledge System Operations Department',
            //     'division' => 'HC BP Delivery and Support Division',
            //     'bgroup' => 'HC Business Partner Group',
            //     'egroup' => null,
            //     'directorate' => 'Human Capital Management Directorate',
            //     'admins' => 'HEAD OFFICE',
            //     'area_group' => 'HEAD OFFICE',
            // ],
            // [
            //     'person_id' => 74587,
            //     'nik' => '85072',
            //     'name' => 'Yoan Eldilian',
            //     'title' =>'Training and Knowledge System Operations Officer',
            //     'organization' => 'Training and Knowledge System Operations Department',
            //     'band' => 2,
            //     'nik_atasan' => '83391',
            //     'nama_atasan' => 'Ivan Yuditia',
            //     'email' => 'Yoan_Eldilian@telkomsel.co.id',
            //     'section' => null,
            //     'department' => 'Training and Knowledge System Operations Department',
            //     'division' => 'HC BP Delivery and Support Division',
            //     'bgroup' => 'HC Business Partner Group',
            //     'egroup' => null,
            //     'directorate' => 'Human Capital Management Directorate',
            //     'admins' => 'HEAD OFFICE',
            //     'area_group' => 'HEAD OFFICE',
            // ],
            // [
            //     'person_id' => 76521,
            //     'nik' => '83391',
            //     'name' => 'Ivan Yuditia',
            //     'title' =>'Manajer Training and Knowledge System Operations',
            //     'organization' => 'Talent and Knowledge System Operations Department',
            //     'band' => 3,
            //     'nik_atasan' => '71070',
            //     'nama_atasan' => 'Vany Yulviany',
            //     'email' => 'Ivan_Yuditia@telkomsel.co.id',
            //     'section' => null,
            //     'department' => 'Training and Knowledge System Operations Department',
            //     'division' => 'HC BP Delivery and Support Division',
            //     'bgroup' => 'HC Business Partner Group',
            //     'egroup' => '',
            //     'directorate' => 'Human Capital Management Directorate',
            //     'admins' => 'HEAD OFFICE',
            //     'area_group' => 'HEAD OFFICE',
            // ],

            // [
            //     'person_id' => 752112,
            //     'nik' => '83395',
            //     'name' => 'HCBP Name',
            //     'title' =>'HCBP Title',
            //     'organization' => 'HCBP Organization',
            //     'band' => 3,
            //     'nik_atasan' => '101010',
            //     'nama_atasan' => 'HCBP Atasan',
            //     'email' => 'Hcbp@telkomsel.co.id',
            //     'section' => null,
            //     'department' => 'HCBP Department',
            //     'division' => 'HCBP Division',
            //     'bgroup' => 'HCBP Partner Group',
            //     'egroup' => '',
            //     'directorate' => 'HCBP Directorate',
            //     'admins' => 'HEAD OFFICE',
            //     'area_group' => 'HEAD OFFICE',
            // ],

            // for testing hcbp 
            [
                'person_id' => 15848,
                'nik' => '71025',
                'name' => 'Fithri Novida',
                'title' =>'Principal Talent and Learning',
                'position_id' => null,
                'organization' => 'Talent and Learning Expert Team',
                'band' => 4,
                'nik_atasan' => '320005',
                'nama_atasan' => 'Mukhammad Atiqurrakhman',
                'email' => 'Fithri_Novida@telkomsel.co.id'  ,
                'section' => null,
                'department' => null,
                'division' => 'Talent and Learning Expert Team',
                'bgroup' => 'People Strategic Management Group',
                'egroup' => null,
                'directorate' => 'Human Capital Management Directorate',
                'admins' => 'HEAD OFFICE',
                'area_group' => 'HEAD OFFICE',
            ],
            [
                'person_id' => 18483,
                'nik' => '81029',
                'name' => 'Nahdatul Choir',
                'title' =>'Senior Learning Architect',
                'position_id' => null,
                'position_id' => '114417',
                'organization' => 'Talent and Learning Expert Team',
                'band' => 3,
                'nik_atasan' => '71025',
                'nama_atasan' => 'Fithri Novida',
                'email' => 'Nahdatul_Choi@telkomsel.co.id',
                'section' => null,
                'department' => null,
                'division' => 'Talent and Learning Expert Team',
                'bgroup' => 'People Strategic Management Group',
                'egroup' => null,
                'directorate' => 'Human Capital Management Directorate',
                'admins' => 'HEAD OFFICE',
                'area_group' => 'HEAD OFFICE',
            ],
            [
                'person_id' => 267445,
                'nik' => '87113',
                'name' => 'Eka Mariska Annisyah',
                'title' =>'Talent and Learning Architect',
                'position_id' => '124461',
                'organization' => 'Talent and Learning Expert Team',
                'band' => 2,
                'nik_atasan' => '71025',
                'nama_atasan' => 'Fithri Novida',
                'email' => 'eka_m_annisyah@telkomsel.co.id',
                'section' => null,
                'department' => null,
                'division' => 'Talent and Learning Expert Team',
                'bgroup' => 'People Strategic Management Group',
                'egroup' => null,
                'directorate' => 'Human Capital Management Directorate',
                'admins' => 'SUMBANGSEL',
                'area_group' => 'AREA 1',
            ],
            [
                'person_id' => 390637,
                'nik' => '92038',
                'name' => 'Tara Aisya Ramadhian',
                'title' =>'Talent and Learning Architect',
                'position_id' => '127257',
                'organization' => 'Talent and Learning Expert Team',
                'band' => 2,
                'nik_atasan' => '71025',
                'nama_atasan' => 'Fithri Novida',
                'email' => 'tara_a_ramadhiani@telkomsel.co.id',
                'section' => null,
                'department' => null,
                'division' => 'Talent and Learning Expert Team',
                'bgroup' => 'People Strategic Management Group',
                'egroup' => null,
                'directorate' => 'Human Capital Management Directorate',
                'admins' => 'SUMBANGSEL',
                'area_group' => 'AREA 1',
            ],
            [
                'person_id' => 396032,
                'nik' => '92101',
                'name' => 'Satya Wicaksana Mukhlisin',
                'title' =>'Training and Knowledge System Operations Officer',
                'position_id' => '128220',
                'organization' => 'Training and Knowledge System Operations Department',
                'band' => 2,
                'nik_atasan' => '83391',
                'nama_atasan' => 'Ivan Yuditia',
                'email' => 'satya_w_mukhlisin@telkomsel.co.id',
                'section' => null,
                'department' => 'Training and Knowledge System Operations Department',
                'division' => 'HC BP Delivery and Support Division',
                'bgroup' => 'HC Business Partner Group',
                'egroup' => null,
                'directorate' => 'Human Capital Management Directorate',
                'admins' => 'JATENG',
                'area_group' => 'AREA 1',
            ],
            [
                'person_id' => 397121,
                'nik' => '93075',
                'name' => 'Annisa Noor Rahmatika',
                'title' =>'Staff Training and Knowledge System Operations',
                'position_id' => '127250',
                'organization' => 'Training and Knowledge System Operations Department',
                'band' => 1,
                'nik_atasan' => '83391',
                'nama_atasan' => 'Ivan Yuditia',
                'email' => 'Annisa_N_Rahmatika@telkomsel.co.id',
                'section' => null,
                'department' => 'Training and Knowledge System Operations Department',
                'division' => 'HC BP Delivery and Support Division',
                'bgroup' => 'HC Business Partner Group',
                'egroup' => null,
                'directorate' => 'Human Capital Management Directorate',
                'admins' => 'HEAD OFFICE',
                'area_group' => 'HEAD OFFICE',
            ],
            [
                'person_id' => 398708,
                'nik' => '93123',
                'name' => 'Joshua Rydley',
                'title' =>'Staff Training and Knowledge System Operations',
                'position_id' => '127252',
                'organization' => 'Training and Knowledge System Operations Department',
                'band' => 2,
                'nik_atasan' => '83391',
                'nama_atasan' => 'Ivan Yuditia',
                'email' => 'joshua_rydley@telkomsel.co.id',
                'section' => null,
                'department' => 'Training and Knowledge System Operations Department',
                'division' => 'HC BP Delivery and Support Division',
                'bgroup' => 'HC Business Partner Group',
                'egroup' => null,
                'directorate' => 'Human Capital Management Directorate',
                'admins' => 'HEAD OFFICE',
                'area_group' => 'HEAD OFFICE',
            ],
            [
                'person_id' => 68236,
                'nik' => '82358',
                'name' => 'Ivren Miraharza Harahap',
                'title' =>'Training and Knowledge System Operations Officer',
                'position_id' => '119262',
                'organization' => 'Training and Knowledge System Operations Department',
                'band' => 2,
                'nik_atasan' => '83391',
                'nama_atasan' => 'Ivan Yuditia',
                'email' => 'ivren_m_harahap@telkomsel.co.id',
                'section' => null,
                'department' => 'Training and Knowledge System Operations Department',
                'division' => 'HC BP Delivery and Support Division',
                'bgroup' => 'HC Business Partner Group',
                'egroup' => null,
                'directorate' => 'Human Capital Management Directorate',
                'admins' => 'HEAD OFFICE',
                'area_group' => 'HEAD OFFICE',
            ],
            [
                'person_id' => 70475,
                'nik' => '85028',
                'name' => 'Fuad Rahadi',
                'title' =>'Senior Talent and Career Architect',
                'position_id' => '127771',
                'organization' => 'Talent and Learning Expert Team',
                'band' => 3,
                'nik_atasan' => '71025',
                'nama_atasan' => 'Fithri Novida',
                'email' => 'Fuad_Rahadi@telkomsel.co.id',
                'section' => null,
                'department' => null,
                'division' => 'Talent and Learning Expert Team',
                'bgroup' => 'People Strategic Management Group',
                'egroup' => null,
                'directorate' => 'Human Capital Management Directorate',
                'admins' => 'HEAD OFFICE',
                'area_group' => 'HEAD OFFICE',
            ],
            [
                'person_id' => 73874,
                'nik' => '85065',
                'name' => 'Vestiyana Rimayumanti',
                'title' =>'Training and Knowledge System Operations Officer',
                'position_id' => '133672',
                'organization' => 'Training and Knowledge System Operations Department',
                'band' => 2,
                'nik_atasan' => '83391',
                'nama_atasan' => 'Ivan Yuditia',
                'email' => 'Vestiyana_Rimayumanti@telkomsel.co.id',
                'section' => null,
                'department' => 'Training and Knowledge System Operations Department',
                'division' => 'HC BP Delivery and Support Division',
                'bgroup' => 'HC Business Partner Group',
                'egroup' => null,
                'directorate' => 'Human Capital Management Directorate',
                'admins' => 'HEAD OFFICE',
                'area_group' => 'HEAD OFFICE',
            ],
            [
                'person_id' => 74587,
                'nik' => '85072',
                'name' => 'Yoan Eldilian',
                'title' =>'Training and Knowledge System Operations Officer',
                'position_id' => null,
                'position_id' => '127777',
                'organization' => 'Training and Knowledge System Operations Department',
                'band' => 2,
                'nik_atasan' => '83391',
                'nama_atasan' => 'Ivan Yuditia',
                'email' => 'Yoan_Eldilian@telkomsel.co.id',
                'section' => null,
                'department' => 'Training and Knowledge System Operations Department',
                'division' => 'HC BP Delivery and Support Division',
                'bgroup' => 'HC Business Partner Group',
                'egroup' => null,
                'directorate' => 'Human Capital Management Directorate',
                'admins' => 'HEAD OFFICE',
                'area_group' => 'HEAD OFFICE',
            ],
            [
                'person_id' => 76521,
                'nik' => '83391',
                'name' => 'Ivan Yuditia',
                'title' =>'Manajer Training and Knowledge System Operations',
                'position_id' => null,
                'organization' => 'Talent and Knowledge System Operations Department',
                'band' => 3,
                'nik_atasan' => '71070',
                'nama_atasan' => 'Vany Yulviany',
                'email' => 'Ivan_Yuditia@telkomsel.co.id',
                'section' => null,
                'department' => 'Training and Knowledge System Operations Department',
                'division' => 'HC BP Delivery and Support Division',
                'bgroup' => 'HC Business Partner Group',
                'egroup' => '',
                'directorate' => 'Human Capital Management Directorate',
                'admins' => 'HEAD OFFICE',
                'area_group' => 'HEAD OFFICE',
            ],

            [
                'person_id' => 752112,
                'nik' => '83395',
                'name' => 'HCBP Name',
                'title' =>'HCBP Title',
                'position_id' => null,
                'organization' => 'HCBP Organization',
                'band' => 3,
                'nik_atasan' => '101010',
                'nama_atasan' => 'HCBP Atasan',
                'email' => 'Hcbp@telkomsel.co.id',
                'section' => null,
                'department' => 'HCBP Department',
                'division' => 'HCBP Division',
                'bgroup' => 'HCBP Partner Group',
                'egroup' => '',
                'directorate' => 'HCBP Directorate',
                'admins' => 'HEAD OFFICE',
                'area_group' => 'HEAD OFFICE',
            ],
        ];

        Employee::insert($employees); // Eloquent approach
    
        // $super_admin = Employee::create([
        //     'nik' => 'Super-admin',
        //     'name' => 'Super Admin Role',
        //     'title' =>'Super Admin',
        //     'organization' => 'Talent and Learning Expert Team',
        //     'band' => 9,
        //     'nik_atasan' => '320005',
        //     'nama_atasan' => 'Mukhammad Atiqurrakhman',
        //     'email' => 'superadmin@role.test',
        //     'section' => null,
        //     'department' => null,
        //     'division' => 'Talent and Learning Expert Team',
        //     'bgroup' => 'People Strategic Management Group',
        //     'egroup' => null,
        //     'directorate' => 'Human Capital Management Directorate',
        //     'admins' => 'HEAD OFFICE',
        //     'area' => 'HEAD OFFICE',
        // ]);

        // $atasan_learning_design = Employee::create([
            // 'id' => 15848,
            // 'nik' => '71025',
            // 'name' => 'Fithri Novida',
            // 'title' =>'Principal Talent and Learning',
            // 'organization' => 'Talent and Learning Expert Team',
            // 'band' => 4,
            // 'nik_atasan' => '320005',
            // 'nama_atasan' => 'Mukhammad Atiqurrakhman',
            // 'email' => 'Fithri_Novida@telkomsel.co.id'  ,
            // 'section' => null,
            // 'department' => null,
            // 'division' => 'Talent and Learning Expert Team',
            // 'bgroup' => 'People Strategic Management Group',
            // 'egroup' => null,
            // 'directorate' => 'Human Capital Management Directorate',
            // 'admins' => 'HEAD OFFICE',
            // 'area' => 'HEAD OFFICE',
        // ]);

        // $learning_desain = Employee::create([
            // 'id' => 18483,
            // 'nik' => '81029',
            // 'name' => 'Nahdatul Choir',
            // 'title' =>'Senior Learning Architect',
            // 'organization' => 'Talent and Learning Expert Team',
            // 'band' => 3,
            // 'nik_atasan' => '71025',
            // 'nama_atasan' => 'Fithri Novida',
            // 'email' => 'Nahdatul_Choi@telkomsel.co.id',
            // 'section' => null,
            // 'department' => null,
            // 'division' => 'Talent and Learning Expert Team',
            // 'bgroup' => 'People Strategic Management Group',
            // 'egroup' => null,
            // 'directorate' => 'Human Capital Management Directorate',
            // 'admins' => 'HEAD OFFICE',
            // 'area' => 'HEAD OFFICE',
        // ]);

        // $learning_desain->assignRole('Learning Design');

        // $karyawan1 = User::create([
            // 'id' => 267445,
            // 'nik' => '87113',
            // 'name' => 'Eka Mariska Annisyah',
            // 'title' =>'Talent and Learning Architect',
            // 'organization' => 'Talent and Learning Expert Team',
            // 'band' => 2,
            // 'nik_atasan' => '71025',
            // 'nama_atasan' => 'Fithri Novida',
            // 'email' => 'eka_m_annisyah@telkomsel.co.id',
            // 'section' => null,
            // 'department' => null,
            // 'division' => 'Talent and Learning Expert Team',
            // 'bgroup' => 'People Strategic Management Group',
            // 'egroup' => null,
            // 'directorate' => 'Human Capital Management Directorate',
            // 'admins' => 'HEAD OFFICE',
            // 'area' => 'HEAD OFFICE',
        // ]);

        // $karyawan2 = User::create([
            // 'id' => 390637,
            // 'nik' => '92038',
            // 'name' => 'Tara Aisya Ramadhian',
            // 'title' =>'Talent and Learning Architect',
            // 'organization' => 'Talent and Learning Expert Team',
            // 'band' => 2,
            // 'nik_atasan' => '71025',
            // 'nama_atasan' => 'Fithri Novida',
            // 'email' => 'tara_a_ramadhiani@telkomsel.co.id',
            // 'section' => null,
            // 'department' => null,
            // 'division' => 'Talent and Learning Expert Team',
            // 'bgroup' => 'People Strategic Management Group',
            // 'egroup' => null,
            // 'directorate' => 'Human Capital Management Directorate',
            // 'admins' => 'HEAD OFFICE',
            // 'area' => 'HEAD OFFICE',
        // ]);

        // $learning_operation = User::create([
        //     'id' => 76521,
        //     'nik' => '83391',
        //     'name' => 'Ivan Yuditia',
        //     'title' =>'Manajer Training and Knowledge System Operations',
        //     'organization' => 'Talent and Knowledge System Operations Department',
        //     'band' => 3,
        //     'nik_atasan' => '71070',
        //     'nama_atasan' => 'Vany Yulviany',
        //     'email' => 'Ivan_Yuditia@telkomsel.co.id',
        //     'section' => null,
        //     'department' => 'Training and Knowledge System Operations Department',
        //     'division' => 'HC BP Delivery and Support Division',
        //     'bgroup' => 'HC Business Partner Group',
        //     'egroup' => '',
        //     'directorate' => 'Human Capital Management Directorate',
        //     'admins' => 'HEAD OFFICE',
        //     'area' => 'HEAD OFFICE',
        // ]);

        // $learning_operation->assignRole('Learning Operation');

        // $karyawan4 = User::create([
            // 'id' => 396032,
            // 'nik' => '92101',
            // 'name' => 'Satya Wicaksana Mukhlisin',
            // 'title' =>'Training and Knowledge System Operations Officer',
            // 'organization' => 'Training and Knowledge System Operations Department',
            // 'band' => 2,
            // 'nik_atasan' => '83391',
            // 'nama_atasan' => 'Ivan Yuditia',
            // 'email' => 'satya_w_mukhlisin@telkomsel.co.id',
            // 'section' => null,
            // 'department' => 'Training and Knowledge System Operations Department',
            // 'division' => 'HC BP Delivery and Support Division',
            // 'bgroup' => 'HC Business Partner Group',
            // 'egroup' => null,
            // 'directorate' => 'Human Capital Management Directorate',
            // 'admins' => 'HEAD OFFICE',
            // 'area' => 'HEAD OFFICE',
        // ]);
    }
}
